# Generated by Django 4.1.3 on 2023-05-07 00:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('descripcion', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_servicio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TipoUsuario',
                'verbose_name_plural': 'tipoUsuarios',
                'db_table': 'tipoUsuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('ap_paterno', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('ap_materno', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(?=.*[a-zA-Z])[\\w@$!%*?&]{3,10}$')])),
                ('direccion', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('fecha_nac', models.DateTimeField()),
                ('telefono', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipousuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='ServicioSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado_servicio', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
            ],
            options={
                'verbose_name': 'ServiciosSolicitado',
                'verbose_name_plural': 'serviciosSolicitados',
                'db_table': 'ServicioSolicitado',
            },
        ),
        migrations.CreateModel(
            name='ServicioOfrecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado_servicio', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
            ],
            options={
                'verbose_name': 'ServicioOfrecido',
                'verbose_name_plural': 'ServiciosOfrecidos',
                'db_table': 'ServicioOfrecido',
            },
        ),
    ]
