# Generated by Django 4.1.3 on 2023-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_usuario_email_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
