# Generated by Django 4.1.3 on 2023-06-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_servicio_usuario_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='servicio_asignado',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to='principal.usuario'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='usuario_realizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.usuario'),
        ),
    ]
